baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Breakit's hugo Site"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-bootstrap-premium"


[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "breakit"
    email = "breakit100@gmail.com"